### build stage
FROM maven:3.9.9-eclipse-temurin-21-alpine AS builder

RUN sed 's/https/http/g' -i /etc/apk/repositories
RUN apk update && apk --no-cache add git

RUN addgroup -S appgroup && adduser -S appuser -G appgroup
USER appuser

ARG USER_ID=Donggeun10
ARG REPOSITORY_ID=support
ARG USER_HOME=/home/appuser
WORKDIR $USER_HOME

RUN git clone https://github.com/$USER_ID/$REPOSITORY_ID.git
WORKDIR $USER_HOME/$REPOSITORY_ID

RUN mvn -B dependency:resolve
RUN mvn package -DskipTests

RUN java -Djarmode=tools -jar target/boot.jar extract --destination application

FROM eclipse-temurin:21-jre-alpine

RUN addgroup -S appgroup && adduser -S appuser -G appgroup
USER appuser

ARG REPOSITORY_ID=support
ARG USER_HOME=/home/appuser
WORKDIR $USER_HOME

# 2) Jar 복사
COPY --from=builder $USER_HOME/$REPOSITORY_ID/application/ ./

# 3) 실행
ENTRYPOINT ["java", "org.springframework.boot.loader.launch.JarLauncher"]