name: support-rest
services:
    webapp:
        image: demo-api:local
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - "9090:8080"
        #command: "--port 9083"
        environment:
            - SPRING_PROFILES_ACTIVE=local
        cpus: 0.2
        mem_limit: 1024m
    webapp-aot:
        image: demo-aot-api:local
        build:
            context: ./
            dockerfile: Dockerfile_aot
        ports:
            - "9091:8080"
        #command: "--port 9083"
        environment:
            - SPRING_PROFILES_ACTIVE=local
        cpus: 0.2
        mem_limit: 1024m
    webapp-cds:
        image: demo-cds-api:local
        build:
            context: ./
            dockerfile: Dockerfile_cds
        ports:
            - "9092:8080"
        #command: "--port 9083"
        environment:
            - SPRING_PROFILES_ACTIVE=local
        cpus: 0.2
        mem_limit: 1024m