logging:
    level:
        root: info
        org.springframework: info
        org.springframework.cache: info
        com.example.support: debug

server:
    port: 8080
    shutdown: graceful
    tomcat:
        threads:
            min-spare: 10
            max: 200

spring:
    application:
        name: application-local
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:mem:homeworkDB;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=3000
        username: sa
        password: sa
        hikari:
            pool-name: homework-pool
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
    h2:
        console:
            enabled: false
            path: /h2-console
    threads:
        virtual:
            enabled: true

management:
    endpoints:
        web:
            exposure:
                include: health,info,sbom
    endpoint:
        health:
            show-details: always

application:
    announcement:
        attachment:
            upload-dir: announcement

okta:
    oauth2:
        client-id: 0oa67bf9b0mgMZY0A357
        client-secret: uYcHzYQl0AaAK8cCMfrgVH1f3RQZRhfQk7LyVFKXRMLzmT9W2HSmzlKw4flSn_FJ
        issuer: https://sso.nmn.io
